### ISSUE TITLE
random freezes when using display port connected to integrated graphics card

### ISSUE THREAD

**Issue by mfmotta** [tuxedocomputers/linux#8]
**OS:** Ubuntu 22.04.3 LTS
**Kernel:** 6.5.0-10008-tuxedo

I'm experiencing random freezes when connecting a monitor via HDMI. At the time of the freeze,`/var/log/syslog ` shows:

`kernel: [ 6399.786110] i915 0000:00:02.0: [drm] *ERROR* [CRTC:131:pipe B] flip_done timed out`

[journalctl logs around the time of the freeze here](https://github.com/tuxedocomputers/linux/files/13415190/journalctl_nov_15_crash.log)

So the problem is related to the graphics driver. Indeed, the crashes happen only when using the HDMI port.

I looked around, (e.g. [0](https://forum.manjaro.org/t/random-freezes-and-horrible-graphics-performances-on-new-laptop/148289), [1](https://www.reddit.com/r/tuxedocomputers/comments/15n9qm7/infinitybook_pro_16_gen_8_pop_os_dual_monitor/), [2](https://gitlab.freedesktop.org/drm/intel/-/issues/8421)) and it seems this can be remediated by downgrading the kernel. I'd like to do that but since you might have some specific patches, I'd like to ask you if have any recommendations.

I'd greatly appreciate a **quick** fix, even if temporary.

**Comment by TheRealAgentK** [comment]
This is essentially the same as this other thread on the Tuxedo Reddit:

https://www.reddit.com/r/tuxedocomputers/comments/17mowcz/screen_freeze_every_morning/

It's not limited to HDMI, for me (and other folks), it occurs on USB-C ports, too.

@mfmotta In the thread I linked, I described how I downgraded to the Tuxedo 6.2 kernel - that has fixed the issue for me for the time being. Obviously not great long-term - but if this was somehow introduced into the Intel graphics driver from upsteam, it'll be almost impossible to be sorted out on Tuxedo's end.

I would suggest though to stop pushing out Kernel 6.5 via `tomte` in case that's still happening.

**Comment by mfmotta** [comment]
Thanks @TheRealAgentK !

For context, this is part of the output of `inxi -Gxxz`  while I'm using both USB-C and HDMI ports (kernel 6.5.0-10008-tuxedo).
```
Graphics:
  Device-1: Intel Raptor Lake-P [Iris Xe Graphics] vendor: Tongfang Hongkong
    driver: i915 v: kernel arch: Gen-13 ports: active: HDMI-A-1,eDP-1
    empty: DP-1,DP-2 bus-ID: 00:02.0 chip-ID: 8086:a7a0

  Device-2: NVIDIA AD107M [GeForce RTX 4060 Max-Q / Mobile]
    vendor: Tongfang Hongkong driver: nvidia v: 535.129.03 arch: Lovelace pcie:
    speed: 5 GT/s lanes: 8 ports: active: none off: DP-3 empty: none
    bus-ID: 01:00.0 chip-ID: 10de:28a0

  Monitor-1: DP-3 mapped: DP-0 note: disabled pos: top-left 

  Monitor-2: HDMI-A-1 mapped: HDMI-1-1 pos: top-right model: Asus VS278

  Monitor-3: eDP-1 mapped: eDP-1-1 pos: primary,bottom-c
```
So it seems HDMI uses the Intel graphics driver and USB-C the NVIDIA driver. So yes, as you said, it's not a problem with the HDMI port itself, but with whatever port which uses the integrated graphics card (e.g. [here](https://forum.manjaro.org/t/random-freezes-and-horrible-graphics-performances-on-new-laptop/148289/11#:~:text=usb%2Dc%20port%20I%20was%20using%20was%20directly%20hardwired%20to%20the%20iGPU) the USB-C port is connected to the Intel iGPU). I might edit the issue title to be more specific.

In the meantime I did downgrade to 6.2.0-10027-tuxedo and also tried 6.2.0-10025 since I had both already installed. However this breaks other things, e.g. `nvidia-smi` can't communicate with the NVIDIA driver, and one of the USB-C ports stops working for the same underlying reason since this is the port that uses the NVIDIA graphics card.

I would really appreciate some assistance from Tuxedo here, even if they could offer only a temporary fix. Downgrading the kernel as I described is not an option for me.
